apiVersion: v1
kind: Pod
metadata:
  name: httptest
  labels:
    app.kubernetes.io/name: httptest
spec:
  containers:
  - name: httptest
    image: server:newer
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 8080
        name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: httptest-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: httptest
  ports:
  - name: http-port
    protocol: TCP
    port: 8080
    targetPort: http-web-svc

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httptest-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httptest-service
            port:
              number: 8080